### ISSUE TITLE
90년대 가요를 중심으로 테스트를 해봤습니다.

### ISSUE THREAD

**Issue by jaegwon** [acidpop/AlsongLyrics#1]
우선 클리앙 닉네임 '보노보노닷컴' 입니다.

테스트 환경 : Synology DS216+, DSM 6.1 Beta, Audio Station 6.0.0.3088

90년대 가요를 중심으로 테스트를 해봤습니다. 대체적으로 약 300곡을 앞부분만 재생을 해봤는데 몇몇곡은 제외하고 대부분 찾아서 표시해주더군요... 상당히 만족스러웠습니다... 특히 알송처럼 구절마다 싱크맞춰서 표시되는점이 신기하네요...

그 못찾아서 표시되지 않는 곡은 알송에서 정상적으로 가사를 표시해주는것도 있었고 알송에서도 표시 못해주는곡도 있었습니다. 

역시 알려주신 로그파일... 수시로 지우라고 하셨었는데... 무시무시 하군요... 단 4곡 재생했을 뿐인데 로그파일 용량은 3MB까지 불어나더군요...

이건 앱 문제이긴 한데 DSM상에서는 정상적으로 표시되는 가사가 안드로이드용 DS Audio에서는 표시가 안되는 경우가 많았습니다. (iOS용은 문제 없는거 같습니다.) - 시놀로지 측에 피드백 해볼 예정입니다.

완성되면 정말 유용한 플러그인이 될꺼 같습니다. 

지금 상태에서도 상당히 괜찮은 동작을 하는거 같은데 로그파일 생성되는 걸 제거하고 바로 공개하고 수정하면서 버전을 올리는것도 괜찮을꺼 같습니다. 충분히 실사용 가능한 수준이네요..

**Comment by acidpop** [comment]
리뷰 감사드립니다. ^^
