### ISSUE TITLE
오 확실히 중국산보다 낫네요

### ISSUE THREAD

**Issue by hahadark** [acidpop/AlsongLyrics#2]
최근에 꽂힌 이소은 노래로 테스트 했습니다. 
중국산은 노래 제목에만 맞춰서 가사를 보내주는듯한게
영어제목이면 노래와 상관없는 가사 나오고
또 흔한 제목이면 다른 노래 가사가 붙는데 안나오는 곡이 없진 않지만
주요 곡들은 다 매칭이 잘 됩니다 
감사합니다!

**Comment by acidpop** [comment]
테스트 리뷰 감사합니다.
