### ISSUE TITLE
좋아요!

### ISSUE THREAD

**Issue by flanli** [acidpop/AlsongLyrics#3]
알송 가사라 다른나라 노래도 알송에 있는거면 한글 가사로 뜨고 좋아요!
가사 싱크도 잘맞는편인데 가사가 한번에 2\~3줄이면 마지막 한줄만 진하게 표시되는 단점이 있지만 그래도 좋은거 같아요\~!
Audio Station은 단점이 많은거 같아서 별로 안썼는데 이제 알송 가사도 나오니 좀더 많이 써봐야겠네요^^

**Comment by acidpop** [comment]
2\~3줄 잘못 표시 되는거는 다른 가사를 선택하시면 될것 같아요\~
