### ISSUE TITLE
tmp 폴더는 어떻게 찾나요?

### ISSUE THREAD

**Issue by hahadark** [acidpop/AlsongLyrics#4]
베타버전에서 만들어진 로그를 삭제하고 싶은데 tmp폴더라는게 어디에 생성되는건가요?

**Comment by acidpop** [comment]
SSH 로 로그인 하셔서 cd /tmp

로 이동 하신 다음
ls -al 명령 쳐 보시면 alsong.log 가 보이실겁니다.

rm alsong.log 하시면 되고

만약 permission denied 가 나오면

sudo -i 로 root 권한으로 로그인 하신 다음 위 과정을 진행 하시면 됩니다.
