### ISSUE TITLE
정말 굿입니다.!!

### ISSUE THREAD

**Issue by zardkim** [acidpop/AlsongLyrics#5]
방금 적용해서 조금 살펴보았는데, 잘 나옵니다. ^^
가사 싱크가 틀리거나 다른 가사를 검색하여 선택하는 버튼은 없는건가요??

**Comment by acidpop** [comment]
PC 에서 Audio Station 접속 하신 다음
해당 음악에서 마우스 우클릭 -> 음악 정보에 들어 가세요.

가사 탭에 가셔서 인터넷 검색 버튼 누르시면 여러개 검색 되는것 중에 하나 선택 하시면 됩니다.

**Comment by zardkim** [comment]
아.. 감사합니다. 거기에 숨어 있었네요~ ㅎ
실시간 가사 나오는 부분에 따로 추가는 어렵겠지요??;;;

**Comment by acidpop** [comment]
그건 Audio Station 자체에 있는 기능이라 제가 건드릴수가 없어요~
시놀로지 측에 건의 하셔야...^^;

**Comment by zardkim** [comment]
네.. 알겠습니다.
아주 잘 쓰겠습니다. ^^ 고생하세요~!
