### ISSUE TITLE
admin계정이 아니면 안되나요?

### ISSUE THREAD

**Issue by otterk** [acidpop/AlsongLyrics#6]
![err](https://user-images.githubusercontent.com/29032982/27372900-1aafbc3e-56a1-11e7-923a-e669bbc1c015.jpg)

admin계정으로 들어가면 가사가 제대로 보이는데,
일반 계정으로 들어가면 스샷과 같은 에러가 나오네요.

**Comment by otterk** [comment]
어드민에서 해당 계정에 song information 편집 권한을 주고 곡별로 Lyrics 에서 Search Internet해서 알송 가사를 직접 입히면 출력이 되네요.
어드민에서는 이렇게 안해도 매칭되는 가사를 바로 보여주는 것 같구요.

**Comment by otterk** [comment]
재접하니까 또 제대로 보이는 것 같기도 하네요 ;;;
죄송합니다.

**Comment by acidpop** [comment]
알송 가사 서버의 상태에 따라 실패 하기도 합니다.
