### ISSUE TITLE
메모리 사용률 폭주로 인한 OOM killer 작동

### ISSUE THREAD

**Issue by jeong840** [acidpop/AlsongLyrics#7]
dsm version : 6.1.3-15152 update 1 
시스템 : i7 + ddr4 32GB

특정 음악 제목에서 cpu/메모리 사용률이 폭주하여 OOM killer가 동작하면서 주요 프로세스들이 죽어버리는 증상이 있습니다.

sh -c php ..... simplexml ..... (이하생략 : 전체 실행 내용을 복사해두려고 했다가 그대로 날려버려서;;)

우선 플러그인을 삭제해서 임시적으로 해결한 상태이나, 해당 문제에 대한 확인을 부탁드립니다.

**Comment by acidpop** [comment]
간혹 가다 알송 서버에서 xml 형식이 아닌 빈 문자열 또는 오류 내용의 문자열이 응답으로 와서 
해당 내용을 SimpleXML 모듈이 처리 하려다가 오류가 나는 것 같습니다.

SimpleXml 처리 이전에 예외 처리 한 다음 다시 업데이트 해볼께요

이슈 등록해주셔서 감사합니다.

**Comment by acidpop** [comment]
그리고 특정 음악 제목을 알려 주시면 테스트 하는데 더 도움이 되니 가능하시다면 알려주세요

**Comment by jeong840** [comment]
담 ( with strings )
파랑새
마왕 (for 魔王)
파애 (for 키르케)

입니다. 여러번 확인을 시도했으나 정확하게는 집어내지 못했고 위 네가지 구간 재생 중 발생했습니다.

**Comment by acidpop** [comment]
http://blog.acidpop.kr/264

일단 0.4 버전 업데이트 하신 다음 테스트 해주세요

**Comment by jeong840** [comment]
테스트 결과 동일한 음악에서는 이상없이 동작중입니다. 다른 음악으로 추가적으로 테스트 해보고 문제가 있으면 다시 남기겠습니다.
업데이트 감사합니다.
