### ISSUE TITLE
일본 노래 등 일부 노래의 경우, 가사을 제대로 찾지 못해요.

### ISSUE THREAD

**Issue by angrystar170** [acidpop/AlsongLyrics#8]
아무래도 태그을 제대로 감지하지 않았나 보는데요.
해결하길 바랄게요..

**Comment by acidpop** [comment]
알송에서는 찾나요?

일본 노래, 일부 노래가 어떤것인지를 알려 주셔야 제가 테스트 해 볼수 있습니다.

**Comment by angrystar170** [comment]
비탄의+아리아+AA+OP+-+Bulls+Eye.mp3
Linked Horizon  - 자유의 날개 (自由の翼)
케모노 프렌즈 OP - 어서오세요 일본공원에[ようこそジャパリパ-クへ]
07. 自由の翼

이정도 입니다.

**Comment by angrystar170** [comment]
또 있어요.
"길가에 버려지다"라는 노래입니다.

**Comment by acidpop** [comment]
노래 제목과 가수 이름 같이 올려주세요

알송 가사는 제목이랑 가수 이름으로 검색합니다

그리고 실제로 알송에서는 가사가 나오나요?

**Comment by angrystar170** [comment]
ドラマチックマーケットライド - 北白川たまこ(CV:洲崎綾)
Bull's Eye - ナノ [비탄의 아리아 aa op]
자유의 날개 (自由の翼) - Linked Horizon 
自由の翼 -  Linked Horizon
길가에 버려지다(noway) - Various Artists
ようこそジャパリパ-クへ - どうぶつビスケッツ×PPP

**Comment by acidpop** [comment]
세번째 질문 드립니다....

알송에서는 가사가 나오나요?

**Comment by angrystar170** [comment]
참고로 [노래이름 - 가수이름]이런식으로 썻어요..

**Comment by angrystar170** [comment]
푸바2000의 알송 플러그인에선 나오는데요..

**Comment by acidpop** [comment]
네 알겠습니다

테스트 해보고 알려드릴께요

**Comment by acidpop** [comment]
"ドラマチックマーケットライド" - "北白川たまこ(CV:洲崎綾)"	X

"Bull's Eye" - "ナノ [비탄의 아리아 aa op]"			X

"자유의 날개 (自由の翼)" - "Linked Horizon"			O

"自由の翼" - "Linked Horizon"					O

"길가에 버려지다(noway)" - "Various Artists"			△ (Artist 명을 비우고 검색 하면 1개 검색 됨)

"ようこそジャパリパ-クへ" - "どうぶつビスケッツ×PPP" 		X


알송 가사 서버측에 직접 스크립트 짜서 돌려본 결과 입니다.

Audio Station 의 경우 가사 검색은 "타이틀" "아티스트" 의 정보만 가지고 검색 하며

알송 가사 서버에서 지원하는 Hash Code 검색은

 Audio Station 에서 지원하지 않습니다.

**Comment by angrystar170** [comment]
알겠어요... 결국 오디오스테이션이 업데이트돼야 한다는군요...
실례했습니다.

**Comment by acidpop** [comment]
알송 자체가 플레이어이기 때문에 해당 파일에 직접적으로 접근이 가능하므로 파일의 Hash code 를 추출해서 검색 할 수 있습니다만..

Audio Station 의 가사 플러그인 은 말 그대로 "플러그인" 구조여서 Audio Station 에서 플러그인으로 title, artist 만 전달해 줍니다.

그렇기 때문에 알송 가사를 검색 할 때 title, artist 만 가지고 검색을 해야 하므로 해당 정보가 없다면 표시가 안됩니다.

꼭 검색해서 듣고 싶으시다면 알송을 설치 하셔서 해당 파일 가사 등록을 이용하여

angrystar170 님이 가지고 계신 제목과 아티스트 이름으로 등록을 해주시면 됩니다.
